CREATE TABLE [dbo].[SFA_REPORTING_FACT_TYPE_MASTER] (
[ID] int NOT NULL IDENTITY(1,1) ,
[REPORTING_FACT_TYPE_NAME] nvarchar(50) NOT NULL ,
[COMMENT] nvarchar(50) NULL ,
[PROJECT_ID] int NULL ,
[PRE_BUILD_SCRIPT] nvarchar(MAX) NOT NULL ,
[BUILD_SCRIPT] nvarchar(MAX) NOT NULL ,
[POST_BUILD_SCRIPT] nvarchar(MAX) NOT NULL ,
[IS_PRODUCT_APPLICABLE] bit NOT NULL ,
[TRANSACTION_LOG_ID] nvarchar(1000) NULL 
)
